on:
    schedule:
    - cron:  "*/15 * * * *"
    workflow_dispatch:
  
  jobs:
    repo-sync:
      name: Sync changes from upstream sppark
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/supranational/sppark.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}